
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5

# development:
#   <<: *default
#   database: MyAccounts_development

# test:
#   <<: *default
#   database: MyAccounts_test
#   username: postgres
#   password:

# production:
#   <<: *default
#   database: MyAccounts_production
#   username: MyAccounts
#   password: <%= ENV['MYACCOUNTS_DATABASE_PASSWORD'] %>

connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: postgres
  password:

development:
  <<: *connection
  database: MyAccounts_development

test: &test
  <<: *connection
  database: MyAccounts_test
